version: '3.3'

networks:
  mauricio:

services:
  karatube:
    image: karatube:latest
    container_name: karatube
    env_file:
      - .env
    volumes:
      - /home/mauricio/karatube_songs:/app/project/static/songs
      - /home/mauricio/karatube_thumbs:/app/project/static/thumbs
#    ports:
#      - 5000:5000
    networks:
      - mauricio
    restart: unless-stopped