version: '3.3'

networks:
  mauricio:

services:
  karatube:
    image: karatube:latest
    container_name: karatube
    env_file:
      - .env
    volumes:
      - /path/to/mp4_videos:/app/project/static/songs
      - /path/to/videos_thumbnails:/app/project/static/thumbs
    ports:
      - 7003:7003
    networks:
      - mauricio
    restart: unless-stopped